# Generated by Django 3.1.2 on 2021-01-09 14:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_Customer', models.BooleanField(default=False)),
                ('is_Restaurant', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara'), ('Izmir', 'Izmir'), ('Antalya', 'Antalya')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('Starter', 'Starter'), ('Salad', 'Salad'), ('Specialty', 'Specialty'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=200, null=True)),
                ('image', models.ImageField(default='static/assets/img/menu/default-product.jpg', upload_to='static/assets/img/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Asian', 'Asian'), ('FastFood', 'FastFood'), ('Desserts', 'Dessert'), ('Bakery', 'Bakery'), ('Pizza', 'Pizza')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userEmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userEmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.registereduser')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='static/assets/img/logo/default-logo.png', upload_to='static/assets/img/logo')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.city')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('userEmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.registereduser')),
                ('restname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=2, null=True)),
                ('rateCount', models.IntegerField(blank=True, default=0, null=True)),
                ('image1', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image2', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image3', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image4', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image5', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('logo', models.ImageField(default='static/assets/img/logo/default-logo.png', upload_to='static/assets/img/logo')),
                ('workingHoursFrom', models.CharField(blank=True, max_length=200, null=True)),
                ('workingHoursTo', models.CharField(blank=True, max_length=200, null=True)),
                ('workingDaysFrom', models.CharField(blank=True, max_length=200, null=True)),
                ('workingDaysTo', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.city')),
                ('tags', models.ManyToManyField(to='store.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
