# Generated by Django 3.1.2 on 2020-12-28 12:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address1', models.CharField(blank=True, max_length=300, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=2, null=True)),
                ('rateCount', models.IntegerField(blank=True, default=0, null=True)),
                ('image1', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image2', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image3', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image4', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('image5', models.ImageField(default='defaultClient.jpg', upload_to='client_pics')),
                ('logo', models.ImageField(default='static/assets/img/logo/default-logo.png', upload_to='static/assets/img/logo')),
                ('workingHoursFrom', models.CharField(blank=True, max_length=200, null=True)),
                ('workingHoursTo', models.CharField(blank=True, max_length=200, null=True)),
                ('workingDaysFrom', models.CharField(blank=True, max_length=200, null=True)),
                ('workingDaysTo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Salad', 'Salad'), ('Specialty', 'Specialty'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/assets/img/menu/default-product.jpg', upload_to='static/assets/img/menu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.restaurant'),
        ),
    ]
