# Generated by Django 3.1.2 on 2021-01-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='is_Customer',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='registereduser',
            old_name='is_Restaurant',
            new_name='is_restaurant',
        ),
    ]
