# Generated by Django 3.1.2 on 2021-01-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210109_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='tags',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(choices=[('Asian', 'Asian'), ('FastFood', 'FastFood'), ('Desserts', 'Dessert'), ('Bakery', 'Bakery'), ('Pizza', 'Pizza')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
