# Generated by Django 3.1.2 on 2020-12-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
