# Generated by Django 3.1.2 on 2020-12-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Asian', 'Asian'), ('FastFood', 'FastFood'), ('Desserts', 'Dessert'), ('Bakery', 'Bakery'), ('Pizza', 'Pizza')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(to='store.Tag'),
        ),
    ]
