# Generated by Django 3.1.2 on 2020-12-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201230_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('Asian', 'Asian'), ('FastFood', 'FastFood'), ('Desserts', 'Dessert'), ('Bakery', 'Bakery'), ('Pizza', 'Pizza')], max_length=200, null=True),
        ),
    ]
