# Generated by Django 3.1.2 on 2020-12-31 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201230_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara'), ('Izmir', 'Izmir'), ('Antalya', 'Antalya')], max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='address1',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.city'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.city'),
        ),
    ]
