# Generated by Django 3.1.2 on 2021-01-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210110_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='surname',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
