# Generated by Django 3.1.2 on 2021-01-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
