# Generated by Django 3.1.2 on 2021-01-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210128_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
