# Generated by Django 3.1.2 on 2021-01-29 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210129_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='store.restaurant'),
        ),
    ]
