# Generated by Django 3.1.2 on 2021-01-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image1',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image2',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image3',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image4',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image5',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
    ]
