# Generated by Django 3.1.2 on 2021-02-03 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_review_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userEmail',
            field=models.OneToOneField(default=76, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
