# Generated by Django 3.1.2 on 2021-02-03 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210203_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userEmail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
